title: Matt Pewsey
author: Matt Pewsey
remote_theme: pages-themes/dinky@v0.2.0
markdown: kramdown
excerpt_separator: <!--excerpt-->
exclude: ['README.md', '*.py', '*.sha256', 'Pipfile', 'Pipfile.lock']
permalink: /:year/:month/:day/:title.html
future: false
plugins:
- jekyll-remote-theme
- jekyll-feed
