title: Matt Pewsey
remote_theme: pages-themes/dinky@v0.2.0
markdown: kramdown
excerpt_separator: <!--excerpt-->
exclude: ['README.md']
permalink: /:year/:month/:day/:title.html
plugins:
- jekyll-remote-theme
